# Serena Project Configuration
project_name: openmanager-ai
project_root: /mnt/d/cursor/openmanager-ai

# Exclude large directories from parsing
exclude_paths:
  - node_modules
  - .next
  - out
  - build
  - dist
  - .git
  - coverage
  - test-results
  - playwright-report
  - "**/*.log"
  - "**/.DS_Store"

# Focus on source code
include_paths:
  - src
  - app
  - pages
  - components
  - lib
  - utils
  - services

# Language servers configuration
language_servers:
  typescript:
    enabled: true
    file_extensions:
      - .ts
      - .tsx
      - .js
      - .jsx
  python:
    enabled: false