import type { ToolSet } from 'ai';
import {
  analyzeLargeLog,
  analyzePattern,
  analyzeScreenshot,
  analyzeUrlContent,
  buildIncidentTimeline,
  computeSeriesStats,
  correlateMetrics,
  detectAnomalies,
  detectAnomaliesAllServers,
  enhanceSuggestedActions,
  estimateCapacityProjection,
  evaluateIncidentReport,
  evaluateMathExpression,
  filterServers,
  finalAnswer,
  findRootCause,
  getServerByGroup,
  getServerByGroupAdvanced,
  getServerLogs,
  getServerMetrics,
  getServerMetricsAdvanced,
  predictTrends,
  recommendCommands,
  refineRootCauseAnalysis,
  scoreRootCauseConfidence,
  searchKnowledgeBase,
  searchWeb,
  searchWithGrounding,
  extendServerCorrelation,
  validateReportStructure,
} from '../../tools-ai-sdk';
import type { AgentToolName } from '../../services/ai-sdk/agents/config/agent-runtime-policy';

export const MONITORING_AGENT_TOOL_REGISTRY: Record<
  AgentToolName,
  ToolSet[string]
> = {
  getServerMetrics,
  getServerMetricsAdvanced,
  filterServers,
  getServerByGroup,
  getServerByGroupAdvanced,
  getServerLogs,
  detectAnomalies,
  detectAnomaliesAllServers,
  predictTrends,
  analyzePattern,
  correlateMetrics,
  findRootCause,
  buildIncidentTimeline,
  searchKnowledgeBase,
  recommendCommands,
  searchWeb,
  evaluateIncidentReport,
  validateReportStructure,
  scoreRootCauseConfidence,
  refineRootCauseAnalysis,
  enhanceSuggestedActions,
  extendServerCorrelation,
  finalAnswer,
  analyzeScreenshot,
  analyzeLargeLog,
  searchWithGrounding,
  analyzeUrlContent,
  evaluateMathExpression,
  computeSeriesStats,
  estimateCapacityProjection,
};

