#!/usr/bin/env ts-node

import fs from 'node:fs';
import path from 'node:path';

const API_ROOT = path.join('src', 'app', 'api');
const OUTPUT_PATH = path.join('docs', 'reference', 'api', 'endpoints.md');
const METHODS = ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'HEAD', 'OPTIONS'];

interface EndpointRecord {
  endpoint: string;
  group: string;
  methods: string[];
  source: string;
}

function walk(dir: string): string[] {
  const out: string[] = [];

  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const fullPath = path.join(dir, entry.name);

    if (entry.isDirectory()) {
      out.push(...walk(fullPath));
      continue;
    }

    if (/^route\.tsx?$/.test(entry.name)) {
      out.push(fullPath);
    }
  }

  return out;
}

function endpointFromRouteFile(filePath: string): string {
  const routeDir = path.dirname(filePath).replaceAll(path.sep, '/');
  const relative = routeDir.replace(/^src\/app\/api\/?/, '');
  return relative ? `/api/${relative}` : '/api';
}

function groupFromEndpoint(endpoint: string): string {
  return endpoint.replace(/^\/api\/?/, '').split('/')[0] || 'root';
}

function exportedMethods(content: string): string[] {
  return METHODS.filter((method) => {
    const patterns = [
      new RegExp(`export\\s+(?:async\\s+)?function\\s+${method}\\b`),
      new RegExp(`export\\s+const\\s+${method}\\b`),
      new RegExp(`export\\s*\\{[^}]*\\b${method}\\b[^}]*\\}`),
    ];

    return patterns.some((pattern) => pattern.test(content));
  });
}

function collectEndpoints(): EndpointRecord[] {
  return walk(API_ROOT)
    .map((source) => {
      const content = fs.readFileSync(source, 'utf8');
      const endpoint = endpointFromRouteFile(source);

      return {
        endpoint,
        group: groupFromEndpoint(endpoint),
        methods: exportedMethods(content),
        source: source.replaceAll(path.sep, '/'),
      };
    })
    .sort((a, b) => a.endpoint.localeCompare(b.endpoint));
}

function render(records: EndpointRecord[]): string {
  const grouped = new Map<string, EndpointRecord[]>();

  for (const record of records) {
    const group = grouped.get(record.group) ?? [];
    group.push(record);
    grouped.set(record.group, group);
  }

  const lines: string[] = [
    '# API Endpoints (Code-Synced)',
    '',
    '> API 엔드포인트 동기화(카탈로그) 레퍼런스',
    '> Owner: platform-architecture',
    '> Status: Active',
    '> Doc type: Reference',
    '> Last reviewed: 2026-05-05',
    '> Canonical: docs/reference/api/endpoints.md',
    '> Tags: api,endpoints,reference',
    '>',
    '> Source of truth: `src/app/api/**/route.ts*`',
    '> Generated by: `npm run docs:api:endpoints`',
    '',
    '이 문서는 **엔드포인트 존재 여부와 라우트 매핑**을 빠르게 확인하기 위한 카탈로그입니다.',
    '각 엔드포인트의 요청/응답 계약(파라미터·헤더·상태코드)은 별도 계약 문서에서 관리합니다.',
    '',
    '> 계약 문서: [API Contracts](./contracts.md)',
    '',
    `총 엔드포인트: **${records.length}**`,
    '',
    '## Summary by Group',
    '',
    '| Group | Count |',
    '|---|---:|',
  ];

  for (const [group, groupRecords] of [...grouped.entries()].sort((a, b) =>
    a[0].localeCompare(b[0])
  )) {
    lines.push(`| ${group} | ${groupRecords.length} |`);
  }

  lines.push('', '## Endpoint Catalog');

  for (const [group, groupRecords] of [...grouped.entries()].sort((a, b) =>
    a[0].localeCompare(b[0])
  )) {
    lines.push(
      '',
      `### /api/${group}`,
      '',
      '| Endpoint | Methods | Source |',
      '|---|---|---|'
    );

    for (const record of groupRecords) {
      const methods =
        record.methods.length > 0 ? record.methods.join(', ') : 'UNKNOWN';
      lines.push(
        `| \`${record.endpoint}\` | \`${methods}\` | \`${record.source}\` |`
      );
    }
  }

  return `${lines.join('\n')}\n`;
}

const records = collectEndpoints();
const nextContent = render(records);
const shouldWrite = process.argv.includes('--write');

if (shouldWrite) {
  fs.writeFileSync(OUTPUT_PATH, nextContent);
  console.log(`Generated ${OUTPUT_PATH} (${records.length} endpoints)`);
  process.exit(0);
}

const currentContent = fs.existsSync(OUTPUT_PATH)
  ? fs.readFileSync(OUTPUT_PATH, 'utf8')
  : '';

if (currentContent !== nextContent) {
  console.error(`${OUTPUT_PATH} is out of sync. Run npm run docs:api:endpoints.`);
  process.exit(1);
}

console.log(`${OUTPUT_PATH} is up to date (${records.length} endpoints)`);
