services:
  renovate:
    image: ghcr.io/renovatebot/renovate:latest
    pull_policy: if_not_present
    env_file:
      - .env
    environment:
      LOG_LEVEL: ${LOG_LEVEL:-info}
      RENOVATE_PLATFORM: ${RENOVATE_PLATFORM:-gitlab}
      RENOVATE_ENDPOINT: ${RENOVATE_ENDPOINT:-https://gitlab.com/api/v4/}
      RENOVATE_REQUIRE_CONFIG: ${RENOVATE_REQUIRE_CONFIG:-required}
      RENOVATE_ONBOARDING: ${RENOVATE_ONBOARDING:-false}
      RENOVATE_AUTODISCOVER: ${RENOVATE_AUTODISCOVER:-false}
