/**
 * GraphRAG Service
 *
 * Retrieval-only GraphRAG runtime: hybrid vector + graph traversal via Supabase pgVector.
 * Indexing and auto-extraction are no longer part of this runtime service.
 *
 * @version 2.1.0
 * @created 2025-12-31
 */

import { createClient, SupabaseClient } from '@supabase/supabase-js';
import { getSupabaseConfig } from './config-parser';
import { logger } from './logger';
import {
  hybridTextVectorSearch,
  type HybridSearchResult as TextSearchResult,
} from './hybrid-text-search';
import {
  fetchRelatedKnowledgeFromGraph,
  mergeDeduplicateAndRankResults,
  traverseAndFetchGraphNodes,
} from './graphrag-graph';
import type {
  GraphRAGSearchResult,
  GraphRAGStats,
} from './graphrag-types';
export type {
  GraphRAGSearchResult,
  GraphRAGStats,
} from './graphrag-types';

// ============================================================================
// Configuration
// ============================================================================

let isInitialized = false;
let supabaseClient: SupabaseClient | null = null;
const EXTRACTION_EDGE_SOURCES = new Set(['llamaindex-triplets', 'title-anchor-fallback']);

function asRecord(value: unknown): Record<string, unknown> | null {
  if (!value || typeof value !== 'object' || Array.isArray(value)) return null;
  return value as Record<string, unknown>;
}

function asArray(value: unknown): unknown[] {
  return Array.isArray(value) ? value : [];
}

/**
 * Initialize GraphRAG service with Supabase client.
 */
export async function initializeGraphRAG(): Promise<boolean> {
  if (isInitialized) return true;

  try {
    const supabaseConfig = getSupabaseConfig();
    if (supabaseConfig) {
      supabaseClient = createClient(
        supabaseConfig.url,
        supabaseConfig.serviceRoleKey
      );
    }

    isInitialized = true;
    logger.info('[GraphRAG] Initialized with Supabase client');
    return true;
  } catch (error) {
    logger.error('[GraphRAG] Initialization failed:', error);
    return false;
  }
}

// ============================================================================
// Vector Search with Supabase pgVector
// ============================================================================

/**
 * Search knowledge base using vector similarity
 * Uses existing Supabase pgVector infrastructure
 */
export async function searchKnowledgeBase(
  query: string,
  options: {
    similarityThreshold?: number;
    maxResults?: number;
    category?: string;
  } = {}
): Promise<GraphRAGSearchResult[]> {
  await initializeGraphRAG();

  const {
    similarityThreshold = 0.4,
    maxResults = 10,
    category,
  } = options;

  if (!supabaseClient) {
    logger.warn('[GraphRAG] Supabase not available');
    return [];
  }

  try {
    // Use Supabase RPC for vector search (embeddings generated by Supabase)
    const { data, error } = await supabaseClient.rpc('match_knowledge_base', {
      query_text: query,
      match_threshold: similarityThreshold,
      match_count: maxResults,
    });

    if (error) throw error;

    const normalizedCategory = category?.trim().toLowerCase();
    const filteredRows = (data || [])
      .filter((row: Record<string, unknown>) => {
        if (!normalizedCategory) return true;
        return String(row.category || '').toLowerCase() === normalizedCategory;
      })
      .slice(0, maxResults);

    return filteredRows.map((row: Record<string, unknown>) => ({
      id: String(row.id),
      title: String(row.title || ''),
      content: String(row.content || ''),
      category: row.category ? String(row.category) : undefined,
      score: Number(row.similarity || 0),
      sourceType: 'vector' as const,
      hopDistance: 0,
      metadata: row.metadata as Record<string, unknown>,
    }));
  } catch (error) {
    logger.error('[GraphRAG] Search failed:', error);
    return [];
  }
}

// ============================================================================
// Hybrid Search (Vector + Knowledge Graph)
// ============================================================================

/**
 * Hybrid search combining vector similarity and knowledge graph traversal
 * Hybrid search: BM25 text search + pgVector similarity
 */
export async function hybridSearch(
  query: string,
  options: {
    similarityThreshold?: number;
    maxVectorResults?: number;
    maxGraphHops?: number;
    maxTotalResults?: number;
  } = {}
): Promise<GraphRAGSearchResult[]> {
  await initializeGraphRAG();

  const {
    similarityThreshold = 0.4,
    maxVectorResults = 5,
    maxGraphHops = 2,
    maxTotalResults = 15,
  } = options;

  if (!supabaseClient) {
    logger.warn('[GraphRAG] Supabase not available');
    return [];
  }

  try {
    // 1. Vector search
    const vectorResults = await searchKnowledgeBase(query, {
      similarityThreshold,
      maxResults: maxVectorResults,
    });

    // 2. Graph traversal from vector results
    const graphResults = await traverseAndFetchGraphNodes(
      supabaseClient!, vectorResults, maxGraphHops
    );

    return mergeDeduplicateAndRankResults(vectorResults, graphResults, maxTotalResults);
  } catch (error) {
    logger.error('[GraphRAG] Hybrid search failed:', error);
    return [];
  }
}

// ============================================================================
// Stats
// ============================================================================

/**
 * Get GraphRAG statistics from Supabase
 */
export async function getStats(): Promise<GraphRAGStats | null> {
  await initializeGraphRAG();

  if (!supabaseClient) return null;

  try {
    const [docsResult, indexedDocsResult, relationshipRowsResult, latestKnowledgeResult] = await Promise.all([
      supabaseClient.from('knowledge_base').select('id', { count: 'exact', head: true }),
      supabaseClient
        .from('knowledge_base')
        .select('metadata')
        .or('metadata->>indexed_by.eq.llamaindex,metadata->>indexed_by.eq.graphrag'),
      supabaseClient
        .from('knowledge_relationships')
        .select('metadata, updated_at')
        .eq('source_table', 'knowledge_base')
        .eq('target_table', 'knowledge_base'),
      supabaseClient
        .from('knowledge_base')
        .select('updated_at')
        .or('metadata->>indexed_by.eq.llamaindex,metadata->>indexed_by.eq.graphrag')
        .order('updated_at', { ascending: false })
        .limit(1),
    ]);

    const indexedRows = Array.isArray(indexedDocsResult.data)
      ? indexedDocsResult.data
      : [];
    const relationshipRows = Array.isArray(relationshipRowsResult.data)
      ? relationshipRowsResult.data
      : [];

    const totalTriplets = indexedRows.reduce((sum, row) => {
      const metadata = asRecord((row as Record<string, unknown>).metadata);
      return sum + asArray(metadata?.triplets).length;
    }, 0);

    const extractionRelationshipRows = relationshipRows.filter((row) => {
      const metadata = asRecord((row as Record<string, unknown>).metadata);
      return EXTRACTION_EDGE_SOURCES.has(String(metadata?.extraction_source || ''));
    });

    const latestCandidates = [
      ...extractionRelationshipRows
        .map((row) => String((row as Record<string, unknown>).updated_at || '').trim())
        .filter((value) => value.length > 0),
      latestKnowledgeResult.data?.[0]?.updated_at,
    ].filter((value): value is string => Boolean(value));

    const lastIndexed =
      latestCandidates.sort((left, right) => {
        return new Date(right).getTime() - new Date(left).getTime();
      })[0] || null;

    return {
      totalDocuments: docsResult.count || 0,
      totalTriplets,
      totalExtractionEdges: extractionRelationshipRows.length,
      lastIndexed,
    };
  } catch (error) {
    logger.error('[GraphRAG] Stats fetch failed:', error);
    return null;
  }
}

// ============================================================================
// Backward Compatibility Exports
// ============================================================================

/**
 * Backward-compatible hybridGraphSearch that accepts embedding array
 * Used by reporter-tools.ts
 *
 * @param queryEmbedding - Query embedding vector (1024 dimensions)
 * @param options - Search options including BM25 text search
 * @returns Array of search results
 */
export async function hybridGraphSearch(
  queryEmbedding: number[],
  options: {
    /** Original query text for BM25 search */
    query?: string;
    /** Enable BM25 text search (requires query) */
    useBM25?: boolean;
    similarityThreshold?: number;
    maxVectorResults?: number;
    maxGraphHops?: number;
    maxTotalResults?: number;
    /** Vector similarity weight (default: 0.5) */
    vectorWeight?: number;
    /** BM25 text search weight (default: 0.3) */
    textWeight?: number;
    /** Graph traversal weight (default: 0.2) */
    graphWeight?: number;
  } = {}
): Promise<GraphRAGSearchResult[]> {
  await initializeGraphRAG();

  const {
    query,
    useBM25 = false,
    similarityThreshold = 0.4,
    maxVectorResults = 5,
    maxGraphHops = 2,
    maxTotalResults = 15,
    vectorWeight = 0.5,
    textWeight = 0.3,
    graphWeight = 0.2,
  } = options;

  // Use BM25 hybrid search if enabled and query text is provided
  if (useBM25 && query) {
    logger.info(`[GraphRAG] Using BM25 hybrid search for: "${query.substring(0, 30)}..."`);

    try {
      const bm25Results = await hybridTextVectorSearch(query, queryEmbedding, {
        vectorWeight,
        textWeight,
        graphWeight,
        maxVectorResults,
        maxTextResults: maxVectorResults,
        maxTotalResults,
        threshold: similarityThreshold,
        maxGraphHops,
      });

      // Convert to GraphRAGSearchResult format
      return bm25Results.map((r: TextSearchResult) => ({
        id: r.id,
        title: r.title,
        content: r.content,
        category: r.category,
        score: r.score,
        sourceType: r.sourceType === 'hybrid' ? 'vector' as const : 'graph' as const,
        hopDistance: r.hopDistance,
        metadata: {
          vectorScore: r.vectorScore,
          textScore: r.textScore,
          graphScore: r.graphScore,
        },
      }));
    } catch (error) {
      logger.warn('[GraphRAG] BM25 search failed, falling back to vector-only:', error);
      // Fall through to vector-only search
    }
  }

  if (!supabaseClient) {
    logger.warn('[GraphRAG] Supabase not available');
    return [];
  }

  try {
    // 1. Direct vector search with embedding
    const { data: vectorData, error: vectorError } = await supabaseClient.rpc('match_documents', {
      query_embedding: queryEmbedding,
      match_count: maxVectorResults,
      filter: {},
    });

    if (vectorError) throw vectorError;

    const vectorResults: GraphRAGSearchResult[] = (vectorData || []).map((row: Record<string, unknown>) => ({
      id: String(row.id),
      title: String(row.title || ''),
      content: String(row.content || ''),
      category: String(row.category || 'auto'),
      score: Number(row.similarity || 0),
      sourceType: 'vector' as const,
      hopDistance: 0,
      metadata: row.metadata as Record<string, unknown>,
    }));

    // 2. Graph traversal from vector results
    const graphResults = await traverseAndFetchGraphNodes(
      supabaseClient!, vectorResults, maxGraphHops
    );

    return mergeDeduplicateAndRankResults(vectorResults, graphResults, maxTotalResults);
  } catch (error) {
    logger.error('[GraphRAG] Hybrid graph search failed:', error);
    return [];
  }
}
export const getGraphRAGStats = getStats;

export const getRelatedKnowledge = async (
  nodeId: string,
  options: { maxHops?: number; maxResults?: number } = {}
) => {
  await initializeGraphRAG();

  if (!supabaseClient) {
    return [];
  }

  return fetchRelatedKnowledgeFromGraph(supabaseClient, nodeId, options);
};
