DROP FUNCTION IF EXISTS public.analyze_performance_trend(text, text);
DROP FUNCTION IF EXISTS public.analyze_query_patterns(interval);
DROP FUNCTION IF EXISTS public.append_conversation_message(text, text, text);
DROP FUNCTION IF EXISTS public.calculate_prediction_accuracy();
DROP FUNCTION IF EXISTS public.calculate_realtime_kpis();
DROP FUNCTION IF EXISTS public.cleanup_expired_agent_context();
DROP FUNCTION IF EXISTS public.cleanup_old_ai_jobs();
DROP FUNCTION IF EXISTS public.cleanup_old_conversations(integer);
DROP FUNCTION IF EXISTS public.cleanup_old_mcp_data();
DROP FUNCTION IF EXISTS public.detect_mcp_anomalies(text, integer);
DROP FUNCTION IF EXISTS public.generate_mcp_aggregates(text, timestamptz, timestamptz);
DROP FUNCTION IF EXISTS public.get_mcp_server_summary(text, integer);
DROP FUNCTION IF EXISTS public.get_metrics_window(text, integer, integer);
DROP FUNCTION IF EXISTS public.get_or_create_conversation(text, text);
DROP FUNCTION IF EXISTS public.get_popular_queries(interval, integer);
DROP FUNCTION IF EXISTS public.get_prediction_performance(character varying, interval);
DROP FUNCTION IF EXISTS public.get_previous_training_stats(text, integer);
DROP FUNCTION IF EXISTS public.get_session_context(character varying);
DROP FUNCTION IF EXISTS public.save_agent_context(character varying, character varying, jsonb, character varying, integer);
